name: sample_assist
description: "A new Flutter project for ID scanning and registration."
# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

# Project dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI related dependencies
  cupertino_icons: ^1.0.8

  # Camera and Image Processing
  camera: ^0.11.0+2
  google_ml_kit: ^0.13.0
  image_picker: ^1.1.2

  # Networking
  http: ^1.2.2

  # Secure storage and local database
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true

  # Asset management
  assets:
    - assets/
    - assets/images/
    - assets/images/logo.png
    - assets/images/bg1.png

  # Custom fonts (if needed in the future)
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

# Dependency management tips
# Run `flutter pub get` to install dependencies
# Run `flutter pub outdated` to check outdated dependencies
